version: '3.8'

networks:
  default:
    external: false
    name: board-app-local

services:
  board-postgres:
    image: 'postgres:13-alpine'
    command: 'postgres -c max_connections=1000'
    restart: always
    container_name: board-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: board
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
