version: '3.8'
networks:
  default:
    external: false
    name: test-app-local

services:
  test-postgres:
    image: postgres:13.2
    command: postgres -c 'max_connections=1000'
    restart: always
    container_name: test-board-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
