version: '3.9'
networks:
  default:
    external: false
    name: board-app-local

services:
  postgres:
    image: postgres:13.2
    container_name: board-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: board-postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
